apiVersion: v1
data:
  config.exs: |
    use Mix.Config

    config :replicator,
      secrets: [
      {{- range $i, $value := .Values.secrets -}}
       {{ if $i }},{{ end }}%{secret: "{{ $value.secret }}", namespace: "{{ $value.namespace }}"}
      {{- end }}]
kind: ConfigMap
metadata:
  name: {{ include "replicator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "replicator.name" . }}
    helm.sh/chart: {{ include "replicator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
