apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "replicator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "replicator.name" . }}
    helm.sh/chart: {{ include "replicator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "replicator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "replicator.name" . }}
    helm.sh/chart: {{ include "replicator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "replicator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "replicator.name" . }}
    helm.sh/chart: {{ include "replicator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "replicator.fullname" . }}
subjects:
  - name: {{ include "replicator.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
